name: notlarim
description: "NotlarÄ±m, Not Defterim"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+11

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  path: ^1.9.1
  intl: ^0.20.2
  sqflite: ^2.4.2
  flutter_staggered_grid_view: ^0.7.0
  file_picker: ^10.3.7
  permission_handler: ^12.0.1
  device_info_plus: ^12.1.0
  package_info_plus: ^9.0.0
  flutter_colorpicker: ^1.1.0
  expandable_richtext: ^1.0.7
  shared_preferences: ^2.5.3
  share_plus: ^12.0.1 
  flutter_riverpod: ^3.0.3
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    # - assets/jsons/
    - assets/logos/
    - assets/lang/
